# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20170225_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='pic',
            field=models.ImageField(upload_to='./images/'),
        ),
    ]
