# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_classphoto_studentphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_group_id', models.CharField(max_length=128)),
                ('student_id', models.CharField(max_length=50)),
                ('person_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=128)),
                ('persisted_id', models.CharField(max_length=128)),
            ],
        ),
    ]
